# Generated by Django 5.1.7 on 2025-11-28 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auxiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('unidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CostoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('unidad', models.CharField(max_length=100)),
                ('costoHorario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cuadrilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('jornada', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EquipoHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('unidad', models.CharField(max_length=100)),
                ('costoUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('clasificacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ManoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('unidad', models.CharField(max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('unidad', models.CharField(max_length=100)),
                ('costoUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('clasificacion', models.CharField(max_length=100)),
                ('colocado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ConceptoAuxiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('auxiliar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepto_auxiliar', to='api.auxiliar')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepto_auxiliar', to='api.concepto')),
            ],
        ),
        migrations.CreateModel(
            name='ConceptoCostoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepto_costo_horario', to='api.concepto')),
                ('costo_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepto_costo_horario', to='api.costohorario')),
            ],
        ),
        migrations.CreateModel(
            name='ConceptoCuadrilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepto_cuadrilla', to='api.concepto')),
                ('cuadrilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepto_cuadrilla', to='api.cuadrilla')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoHerramientaAuxiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('auxiliar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_herramienta_auxiliar', to='api.auxiliar')),
                ('equipo_herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_herramienta_auxiliar', to='api.equipoherramienta')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoHerramientaConcepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_herramienta_concepto', to='api.concepto')),
                ('equipo_herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_herramienta_concepto', to='api.equipoherramienta')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoHerramientaCuadrilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('cuadrilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_herramienta_cuadrilla', to='api.cuadrilla')),
                ('equipo_herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_herramienta_cuadrilla', to='api.equipoherramienta')),
            ],
        ),
        migrations.CreateModel(
            name='ManoObraAuxiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('auxiliar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mano_obra_auxiliar', to='api.auxiliar')),
                ('mano_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mano_obra_auxiliar', to='api.manoobra')),
            ],
        ),
        migrations.CreateModel(
            name='ManoObraConcepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mano_obra_concepto', to='api.concepto')),
                ('mano_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mano_obra_concepto', to='api.manoobra')),
            ],
        ),
        migrations.CreateModel(
            name='ManoObraCuadrilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('cuadrilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mano_obra_cuadrilla', to='api.cuadrilla')),
                ('mano_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mano_obra_cuadrilla', to='api.manoobra')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialAuxiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('auxiliar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_auxiliar', to='api.auxiliar')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_auxiliar', to='api.material')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialConcepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_concepto', to='api.concepto')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_concepto', to='api.material')),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material', to='api.obra'),
        ),
        migrations.AddField(
            model_name='manoobra',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mano_obra', to='api.obra'),
        ),
        migrations.AddField(
            model_name='equipoherramienta',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_herramienta', to='api.obra'),
        ),
        migrations.AddField(
            model_name='cuadrilla',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuadrilla', to='api.obra'),
        ),
        migrations.AddField(
            model_name='costohorario',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costo_horario', to='api.obra'),
        ),
        migrations.AddField(
            model_name='concepto',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept', to='api.obra'),
        ),
        migrations.AddField(
            model_name='auxiliar',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auxiliar', to='api.obra'),
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partida', to='api.obra')),
            ],
        ),
        migrations.CreateModel(
            name='PartidaPadreHijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partida_padre_hijo', to='api.obra')),
                ('partidaHijo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partida_hijo', to='api.partida')),
                ('partidaPadre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partida_padre', to='api.partida')),
            ],
        ),
        migrations.AddField(
            model_name='concepto',
            name='PartidaPadreHijo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepto', to='api.partidapadrehijo'),
        ),
    ]
