# Generated by Django 5.1.7 on 2025-12-07 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concepto',
            name='PartidaPadreHijo',
        ),
        migrations.AddField(
            model_name='concepto',
            name='partida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='concepto', to='api.partida'),
            preserve_default=False,
        ),
    ]
