# Generated by Django 6.0 on 2025-12-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_concepto_partidapadrehijo_concepto_partida'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='calle',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obra',
            name='codigoPostal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obra',
            name='estado',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obra',
            name='municipio',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obra',
            name='numero',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
