# Generated by Django 6.0 on 2025-12-18 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_obra_calle_obra_codigopostal_obra_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupoTrabajo', to='api.obra')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=100)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupoUsuarios', to='api.grupotrabajo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupoUsuarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
